### ISSUE TITLE
Unhandled rejection TypeErrorについて質問

### ISSUE THREAD

**Issue by tm-qc** [mitsuruog/hexo-theme-simple-japanese#10]
初めまして。突然の質問申し訳ありません。
インストールして起動したところ、以下のエラーが出て解消できません。

一応　_config.yml.example　を　_config.ymlに変更は試しました。
もしよければアドバイスいただけませんでしょうか。

知識不足申し訳ありません。
よろしくお願いします。

---------
Unhandled rejection TypeError: /Users/ユーザフォルダ/ブログフォルダ/themes/simple-japanese/layout/layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2| <body>
    3|   <%- partial('_partial/google-analytics', { head: false }) %>
    4|   <%- partial('_partial/header') %>

/Users/ユーザフォルダ/ブログフォルダ/themes/simple-japanese/layout/_partial/head.ejs:20
    18|   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    19|   <%- css('css/style') %>
 >> 20|   <% if (config.simple_japanese.custom_assets.css) { %>
    21|     <%- css(config.simple_japanese.custom_assets.css) %>
    22|   <% } %>
    23|   <%- partial('gen-structured-data') %>

Cannot read property 'custom_assets' of undefined
    at eval (eval at compile (/Users/ユーザフォルダ/ブログフォルダ/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:35:35)
    at returnedFn (/Users/ユーザフォルダ/ブログフォルダ/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync (/Users/ユーザフォルダ/ブログフォルダ/node_modules/hexo/lib/theme/view.js:121:22)
    at Theme._View.View.View.renderSync (/Users/ユーザフォルダ/ブログフォルダ/node_modules/hexo/lib/theme/view.js:49:23)
    at Object.partial (/Users/ユーザフォルダ/ブログフォルダ/node_modules/hexo/lib/plugins/helper/partial.js:38:15)
    at eval (eval at compile (/Users/ユーザフォルダ/ブログフォルダ/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:9:17)
    at returnedFn (/Users/ユーザフォルダ/ブログフォルダ/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled (/Users/ユーザフォルダ/ブログフォルダ/node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render (/Users/ユーザフォルダ/ブログフォルダ/node_modules/hexo/lib/theme/view.js:30:15)
    at /Users/ユーザフォルダ/ブログフォルダ/node_modules/hexo/lib/theme/view.js:41:23
    at tryCatcher (/Users/ユーザフォルダ/ブログフォルダ/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ユーザフォルダ/ブログフォルダ/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/ユーザフォルダ/ブログフォルダ/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/ユーザフォルダ/ブログフォルダ/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/ユーザフォルダ/ブログフォルダ/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/ユーザフォルダ/ブログフォルダ/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/ユーザフォルダ/ブログフォルダ/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/ユーザフォルダ/ブログフォルダ/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ユーザフォルダ/ブログフォルダ/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)

**Comment by mitsuruog** [comment]
@tm-qc 気づかなくてすみません。

まず起動とは`npm start`で間違いないでしょうか？

エラーの内容を見る感じだと`_config.yml`の内容が正しくない可能性があります。
お手数ですが、次の情報を教えてもらうことは可能ですか？

- Hexoのversion
- _config.ymlの内容

**Comment by tm-qc** [comment]
確認ありがとうございます。
こちらもCLOSEしておらず申し訳ありません。

時間がたってしまい、landscapeテーマをカスタマイズして利用する運用で開始してしまったので、当時の_config.ymlがもうありません。

本件はCLOSEさせていただきます。
お手数おかけして申し訳ありませんでした..。

今後ご縁があった際は、是非またよろしくお願い致します。
