### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by hidaris** [mitsuruog/hexo-theme-simple-japanese#9]
Hi, thanks for this theme, I ran into a few errors when running hexo server
```
Unhandled rejection TypeError: /Users/hidaris/Blog/themes/simple_japanese/layout/layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2| <body>
    3|   <%- partial('_partial/google-analytics', { head: false }) %>
    4|   <%- partial('_partial/header') %>

/Users/hidaris/Blog/themes/simple_japanese/layout/_partial/head.ejs:20
    18|   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    19|   <%- css('css/style') %>
 >> 20|   <% if (config.simple_japanese.custom_assets.css) { %>
    21|     <%- css(config.simple_japanese.custom_assets.css) %>
    22|   <% } %>
    23|   <%- partial('gen-structured-data') %>

Cannot read property 'custom_assets' of undefined
    at eval (eval at compile (/Users/hidaris/Blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:35:34)
    at returnedFn (/Users/hidaris/Blog/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/hidaris/Blog/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/Users/hidaris/Blog/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/hidaris/Blog/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/Users/hidaris/Blog/node_modules/lodash/lodash.js:4949:19)
    at eval (eval at compile (/Users/hidaris/Blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:9:17)
    at returnedFn (/Users/hidaris/Blog/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/hidaris/Blog/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/Users/hidaris/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at _compiled.then.result (/Users/hidaris/Blog/node_modules/hexo/lib/theme/view.js:40:23)
    at tryCatcher (/Users/hidaris/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/hidaris/Blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/hidaris/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/hidaris/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/hidaris/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/hidaris/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/hidaris/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/hidaris/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```
Any suggestions?

**Comment by oahccc** [comment]
I've encountered the same issue.

**Comment by tm-qc** [comment]
同じ状態で解決できません。
